<a href="https://colab.research.google.com/github/Bibhukalyan/MvvmPractice/blob/master/L1_Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Tutorial

## 1. Basics

In [ ]:
import numpy as np

## 2. Making arrays

In [ ]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


(3,)

In [ ]:
lol1 = [[[1.2, 3.4, 5.6], [5.4,3.2,2.1], [12, 1, 2]], [[1.2, 3.4, 5.6], [5.4,3.2,2.1], [12, 1, 2]]]
lol2 = [[1.2, 3.4, 5.6], [5.4,3.2,2.1], [12, 1, 2]]


b1 = np.array(lol1)
print(b1)
b2 = np.array(lol2)
print(b2)

[[[ 1.2  3.4  5.6]
  [ 5.4  3.2  2.1]
  [12.   1.   2. ]]

 [[ 1.2  3.4  5.6]
  [ 5.4  3.2  2.1]
  [12.   1.   2. ]]]
[[ 1.2  3.4  5.6]
 [ 5.4  3.2  2.1]
 [12.   1.   2. ]]


In [ ]:
# Get Dimension
a.ndim, b1.ndim

(1, 3)

In [ ]:
# Get Shape
b1.shape, b2.shape

((2, 3, 3), (3, 3))

In [ ]:
# Get type
print(a.dtype)
a = np.array([1, 2, 3], dtype=np.int16) # 'int16'
print(a.dtype)
print(b1.dtype)

int64
int16
float64


In [ ]:
# Get Size
print(a.size)
print(a.itemsize) # 2 because we have used int16, 4 if int32
print(b1.itemsize)

3
2
8


In [ ]:
# Total Size
b1.nbytes, (b1.itemsize*b1.size)

(144, 144)

### 2.1 Accessing/Changing Specefix Elements, rows, columns etc.

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a1 = list(range(1, 100))
print(a1[49])
print(lol1[0])
print(lol1[0][1])
print(lol1[0][1][2])

50
[[1.2, 3.4, 5.6], [5.4, 3.2, 2.1], [12, 1, 2]]
[5.4, 3.2, 2.1]
2.1


In [ ]:
# get a specefic element
a[1,5]

13

In [ ]:
a1[:]
a1[0:len(a1)]
a1[0:-1]


# get a specefic row
a[1, :]
# get a specefic col
# a[:, 2]

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
# get a specefic column
a[:, 3]

array([ 4, 11])

In [ ]:
a1[0:25:5]
print(a)
# getting little more fancy, [startindex:endindex:stepsize]
a[0, 1:-1:2] #a[0, 1:6:2]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([2, 4, 6])

In [ ]:
# change
a[1, 3] = 21.2
a[1,5] = 20
print(a)
print()
a[:, 2] = [34,68]
print(a)

a[0, 2:4] = [1, 2]
a

[[ 1  2  1  2  5  6  7]
 [ 8  9 68 21 12 20 14]]

[[ 1  2 34  2  5  6  7]
 [ 8  9 68 21 12 20 14]]


array([[ 1,  2,  1,  2,  5,  6,  7],
       [ 8,  9, 68, 21, 12, 20, 14]])

In [ ]:
# 3d array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
c[0,1,1] # from 0th clusters/dimension 2nd row get 2nd element i.e 4

4

In [ ]:
print(c[:,1,:]) # from both clusters get 2nd row
print("\n", c[:,:,1]) # from all clusters all rows get 2nd column

[[3 4]
 [7 8]]

 [[2 4]
 [6 8]]


### 2.2 Initializing different types of arrays

In [ ]:
# all zeros
z1 = np.zeros((3,3,3)) # basically a  cube containing zeros
print(z1)
z2 = np.zeros((2,2))
print("\n", z2)
z1.dtype

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]

 [[0. 0.]
 [0. 0.]]


dtype('float64')

In [ ]:
# all ones
np.ones((3,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
# any other numbers
np.full((2,2), 32, dtype='float32')

array([[[9, 9, 9],
        [9, 9, 9]]])

In [ ]:
# full_like
np.full_like(a,4) #np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# array of random numbers
# r21 = np.random.randint(0, 10, (2, 2))

r1 = np.random.randn(4,5)
# r1 = np.random.rand(4,2) # Uniform Distribution
print(r1)
# r2 = np.random.random_sample(a.shape)
# print("\n", r2)

[[-1.45304628 -0.6942839   0.5659518  -1.26863294 -1.83904919]
 [ 0.87894335  0.57835336  0.84737431 -0.55545749 -0.70870905]
 [-2.36532764  0.60401145  2.40402197  1.29168546 -0.6824735 ]
 [-0.42236112 -0.92256689  0.19947151 -0.26560625 -0.60845275]]


In [ ]:
# random int array
np.random.randint(10, size=(3,3))

array([[0, 2, 9],
       [6, 7, 4],
       [1, 5, 6]])

In [ ]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# repeat an array
arr = np.array([1,2,3])
rep = np.repeat(arr, 3, axis=0)
print(rep)

arr = np.array([[1,2,3]])
rep2 = np.repeat(arr, 3, axis=0)
print("\n",rep2)

[1 1 1 2 2 2 3 3 3]

 [[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# problem 1: generate the array usnig initialization methods
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1

output = np.ones((5,5))
print(f"{output} \n")

z = np.zeros((3,3))
z[1,1] = 9
output[1:-1, 1:-1] = z
print(f"{output} \n")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]] 



### 2.3 Be careful while copying arrays !!!

In [ ]:
print("POINTING!")
a = np.array([1,2,3])
b = a 
print(f"b.initial = {b}")
b[0] = 100
print(f"b = {b}")
# Assignment did not copy it pointed b to a, thus change in b means change in a
print(f"a = {a} \n")

print("COPYING!")
m = np.array([10,20,30])
n = m.copy() 
print(f"n.initial = {n}")
n[0] = 1000
print(f"n = {n}")
# Assignment did not copy it pointed b to a, thus change in b means change in a
print(f"m = {m}")

POINTING!
b.initial = [1 2 3]
b = [100   2   3]
a = [100   2   3] 

COPYING!
n.initial = [10 20 30]
n = [1000   20   30]
m = [10 20 30]


## 3. Mathematics

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a += 2
a

array([3, 4, 5, 6])

In [ ]:
a -= 2
a

array([1, 2, 3, 4])

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
1/2

0.5

In [ ]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [ ]:
a ** 2

np.power(a, 2)

array([ 1,  4,  9, 16])

In [ ]:
# trigonometry
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### 3.1 Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(f"\n {b}")

[[1. 1. 1.]
 [1. 1. 1.]]

 [[2 2]
 [2 2]
 [2 2]]


In [ ]:
# matrix multiplication
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
# determinant
a23 = np.array([[1, 2], [3, 4]])

c = np.full((3, 3), 2)
np.linalg.det(a23)

-2.0000000000000004

In [ ]:
np.dot(a, a.transpose())
a.transpose()

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# reference docs : https://numpy.org/doc/stable/reference/routines.linalg.html

### 3.2 Statistics

In [ ]:
stats = np.array([[1,2,3], [5,6,7]])
stats

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
min1 = np.min(stats, axis=0) # returns min of each row
min2 = np.min(stats, axis=1) # returns a list containing min for each column
print(min1) 
print(min2)

[1 2 3]
[1 5]


In [ ]:
m = np.max(stats)
m

7

In [ ]:
print(np.sum(stats))
print(np.sum(stats, axis=0)) # sum of all the rows

24
[ 6  8 10]


In [ ]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(f"{before} \n")

after = before.reshape((8,1))
print(f"{after} \n") #column vector

print(before.reshape((2,-1,2)))

[[1 2 3 4]
 [5 6 7 8]] 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]] 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(v1, v2, np.vstack([v1, v2])) # combines array vertically

# Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(f"\n {np.hstack([h1,h2])}")

[1 2 3 4] [5 6 7 8] [[1 2 3 4]
 [5 6 7 8]]

 [[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


## 4. Miscellaneous

#### Load Data from a File

In [ ]:
filedata = np.genfromtxt('data/data.txt', delimiter=',').astype('int32') 
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

#### Boolean Masking and Advanced Indexing

In [ ]:
# you can index with a list in numpy
# example
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,3,4]]

array([2, 3, 4, 5])

In [ ]:
z = filedata > 50
print(z)
zee = filedata[filedata > 50] # you can index with a list in numpy
print(f"\n {zee}") 

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]

 [196  75 766  75  55 999  78  76  88]


In [ ]:
np.any(filedata>50, axis=0) # axis = 0 means in the column 

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [ ]:
np.all(filedata>25, axis=1) # axis = 0 means in the column 

array([False, False, False])

In [ ]:
(~((filedata>50) & (filedata <100))) # ~ means not

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

## 5. Problems

**Q: Index the highlighted elements of the array**

![image.png](attachment:fa600173-43b0-482b-9d88-32c15ba01ada.png)

In [ ]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
# Solution 1
a[2:4, 0:2] 

array([[11, 12],
       [16, 17]])

In [ ]:
# solution 2
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [ ]:
# Solution 3
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

## 6. Exercises

### 6.1: Circle Fitting

Fit a circle through points a1 = (0,0), a2 = (1/2,0), a3 = (1,0), a4 = (1,1), a5 = (0,1)

Formula is :   
$y = (A^TA)^{-1}A^Tb $

In [ ]:
A = np.array([[0,0,-1], [1,0,-1], [2,0,-1], [2,2,-1], [0,2,-1]]) # making the A array
A_star = np.matmul(A.T, A) # (AA^T)
A_inv = np.linalg.inv(A_star) # (AA^T)^(-1)
b = np.array([0, 0.25, 1,  2, 1]) # b vector
f = np.matmul(A_inv, A.T) # final multiplication before multiplying to b
y = np.matmul(f, b.T) # calculation of y
x_hat = y[0:2]
R = y[2]
r = np.sqrt(np.linalg.norm(x_hat)**2 - R)

print("A_star: ", A_star)
#print("A_inv: ", A_inv)
#print("\nf: ", f)
print(f'\ny = {y}')
print('Centres (x, y) are: ({:.3f}, {:.3f})'.format(x_hat[0],x_hat[1]))
print('Radius of the circle is {:.2f}'.format(r))

A_star:  [[ 9  4 -5]
 [ 4  8 -4]
 [-5 -4  5]]

y = [0.5        0.54166667 0.08333333]
Centres (x, y) are: (0.500, 0.542)
Radius of the circle is 0.68


### 6.2: DFP Method

In [ ]:
p = np.array([[84/17], [-42/17]])
q = np.array([[56/17], [41/17]])

A1 = np.matmul(p, p.T)
A2 = np.matmul(p.T, q)

In [ ]:
x = float(A2)
A = A1/x
A

array([[ 2.36619718, -1.18309859],
       [-1.18309859,  0.5915493 ]])

In [ ]:
S = np.identity(2)
B1_1 = np.matmul(S, q)
B1_2 = np.matmul(q.T, S.T)
B1 = np.matmul(B1_1, B1_2)
B2_1 = np.matmul(q.T, S)
B2 = np.matmul(B2_1, q)
B2 = float(B2)
#B = B1/B2
#S + A - B
grad_X1 = np.array([[90/17], [24/17]])

In [ ]:
s1 = np.array([[2.715, -1.66], [-1.66, 1.242]])
d1 = -np.matmul(s1, grad_X1)
x1 = np.array([50/17, 26/17])
d1

array([[-12.03      ],
       [  7.03482353]])

### 6.3: Goodman's Co-efficient

In [ ]:
# Goodmans Coefficient

observation = [[12, 25, 32, 11], [17, 18, 22, 23], [21, 17, 16, 26]]
expectation = [[4, 25/3, 32/3, 11/3], [17/3, 6, 22/3, 23/3], [7, 17/3, 16/3, 26/3]]

def goodman(observation, expectation):
    G=0
    for i in range(len(observation)):
        for j in range(len(observation[0])):
            G += ((observation[i][j] - expectation[i][j])**2)/expectation[i][j]
            print(G)
    return G

print(goodman(observation, expectation))

16.0
49.33333333333332
92.0
106.66666666666667
129.33333333333334
153.33333333333334
182.66666666666669
213.33333333333334
241.33333333333334
264.0
285.3333333333333
320.0
320.0


In [ ]:
O = [[10, 15, 30], [8, 17, 20]]
E = [[5.5, 8.25, 16.5], [3.6, 7.65, 9]]

print(goodman(O, E))

3.6818181818181817
9.204545454545453
20.25
25.62777777777778
37.05555555555556
50.5
50.5


In [ ]:
# Correlation Coefficient
X = [1,2,7,4,6,8,11,5,10,11]
Y = [7,11,4,10,8,9,2,5,1,3]
X = np.array(X)
Y = np.array(Y)

np.mean(X), np.mean(Y), np.var(X), np.var(Y), np.cov(X), np.cov(Y), np.cov(X, Y)

(6.5,
 6.0,
 11.45,
 11.0,
 array(12.72222222),
 array(12.22222222),
 array([[12.72222222, -9.22222222],
        [-9.22222222, 12.22222222]]))